version: '2'
services:
    prismoakjob-app:
        image: prismoakjob
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://prismoakjob-mysql:3306/prismoakjob?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://prismoakjob-elasticsearch:9200
        ports:
            - 8042:8042
    prismoakjob-mysql:
        extends:
            file: mysql.yml
            service: prismoakjob-mysql
    prismoakjob-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: prismoakjob-elasticsearch
